#!/bin/sh

if ! command -v git &>/dev/null; then
  read -n1 -rep "O git não está instalado. Deseja instalá-lo agora? (s/n)" RES
  if [[ $RES == [Ss] ]]; then
    printf "\e[33m Instalando o git...\e[0m \n"
    sudo pacman -S --noconfirm git
    printf "\e[32m Instalação concluída!\e[0m \n"
  fi
fi

printf "\e[32m Clonando projeto...\e[0m \n"
sleep 1
git clone https://github.com/afiovinicius/dotfiles.git
cd "$HOME/dotfiles"
"./setup.sh"