#!/bin/sh

if ! command -v git &>/dev/null; then
  read -n1 -rep "O git não está instalado. Deseja instalá-lo agora? (s/n)" RES
  if [[ $RES == [Ss] ]]; then
    printf "\e[33m Instalando o git...\e[0m \n"
    sudo pacman -S --noconfirm git
    printf "\e[32m Instalação concluída!\e[0m \n"
  fi
fi

if [ ! -d "$HOME/dotfiles" ]; then
  printf "\e[32m Clonando projeto...\e[0m \n"
  sleep 0.5
  git clone https://github.com/afiovinicius/dotfiles.git
  git -C "$HOME/dotfiles" checkout .
  "./setup.sh"
  printf "\e[32m Projeto clonado com sucesso!\e[0m \n"
else
  printf "\e[32m A pasta dotfiles já existe. Pulando a clonagem.\e[0m \n"
fi
