#!/bin/sh

DOTFILES_DIR="$HOME/.dotfiles"
MISSING_PKGS=""

if ! command -v git >/dev/null 2>&1; then MISSING_PKGS="$MISSING_PKGS git"; fi
if ! command -v lua >/dev/null 2>&1; then MISSING_PKGS="$MISSING_PKGS lua luarocks"; fi
if ! command -v gum >/dev/null 2>&1; then MISSING_PKGS="$MISSING_PKGS gum"; fi

if [ -n "$MISSING_PKGS" ]; then
  printf "\e[33m Instalando dependências base ($MISSING_PKGS)...\e[0m \n"
  sudo pacman -S --noconfirm $MISSING_PKGS
  printf "\e[32m Instalação concluída!\e[0m \n"
fi

if [ ! -d "$DOTFILES_DIR" ]; then
  printf "\e[32m Clonando projeto...\e[0m \n"
  sleep 0.5
  git clone https://github.com/afiovinicius/dotfiles.git "$DOTFILES_DIR"
  printf "\e[32m Projeto clonado com sucesso!\e[0m \n"
else
  printf "\e[33m A pasta .dotfiles já existe. Pulando a clonagem.\e[0m \n"
fi

cd "$DOTFILES_DIR" || exit

if [ -d ".git" ] && [ -f "./src/main.lua" ]; then
  git checkout . && git pull > /dev/null 2>&1

  # Instalação de dependências do Luarocks (Descomente se precisar!)
  # printf "\e[34m Instalando dependências do Lua...\e[0m \n"
  # sudo luarocks install nome_do_pacote

  printf "\e[34m Iniciando o instalador...\e[0m \n"
  lua "./src/main.lua"
else
  printf "\e[31m Erro crítico: O diretório não contém o projeto esperado ou está corrompido.\e[0m \n"
  printf "\e[31m Verifique se o caminho $DOTFILES_DIR está correto ou apague a pasta e rode o script novamente.\e[0m \n"
  exit 1
fi