#!/bin/sh

## init block ##
#~~|¨Colors¨|~~#
COLOR_RESET="\e[0m"
COLOR_BLACK="\e[30m"
COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_PURPLE="\e[34m"
COLOR_CYAN="\e[36m"
COLOR_WHITE="\e[37m"
## end block ##

## init block ##
#~~|¨Variables¨|~~#
DIR_USER=$HOME
DIR_NAV=$PWD
DIR_FILES=$DIR_NAV/files
## end block ##

## init block ##
#~~|¨Functions¨|~~#
pf() {
  local TIME="\e[1m$COLOR_PURPLE$(date +"%H:%M:%S")$COLOR_RESET"
  local MESSAGE="$1"
  local COLOR="$2"

  case "$COLOR" in
      "error")
          COLOR_CODE=$COLOR_RED;;
      "warn")
          COLOR_CODE=$COLOR_YELLOW;;
      "success")
          COLOR_CODE=$COLOR_GREEN;;
      *)
          COLOR_CODE=$COLOR_CYAN;; 
  esac

  printf "\n$TIME - $COLOR_CODE$MESSAGE$COLOR_RESET\n"
}
## end block ##