#!/bin/sh

DEFAULT_DIR="$HOME/.config/bspwm"

xsetroot -cursor_name left_ptr

#-----Scripts-----#
$DEFAULT_DIR/scripts/set_wallpaper.sh

#-----Interface Start-----#
polybar &
pkill dunst
dunst &
pkill picom
picom -b &
pkill sxhkd
sxhkd &

#-----BSPWM Settigns-----#
bspc monitor -d I II III IV V

bspc config window_gap  8
bspc config top_padding 16
bspc config border_width  0.50

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner