# Vicit Alacritty Colors

# Default colors
[colors.primary]
background = '#15151F'
foreground = '#CACAE8'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff646d'
green   = '#22c55e'
yellow  = '#db8c25'
blue    = '#3b82f6'
magenta = '#ec4899'
cyan    = '#14b8a6'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa0a6'
green   = '#86efac'
yellow  = '#e8b75c'
blue    = '#93c5fd'
magenta = '#f9a8d4'
cyan    = '#5eead4'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#EBC771'

[[colors.indexed_colors]]
index = 17
color = '#FF414C'
