"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[@$hostname]($style) '
style = "bold green"

[directory]
truncation_length = 3
style = "blue"

[cmd_duration]
min_time = 500
format = ' 󱦟 $duration($style)'

[docker_context]
format = '$symbol$context($style)'

[git_branch]
symbol = " "

[nodejs]
symbol = " "
format = '[$symbol($version)]($style)'

[package]
format = '[$symbol$version]($style) '

[python]
format = '${symbol}${pyenv_prefix}[(${version}) (\($virtualenv\))]($style)'

[rust]
format = '[$symbol($version)]($style)'

[solidity]
format = '[$symbol($version)]($style)'
